doctrine:
    dbal:
        # Driver PostgreSQL
        driver: pdo_pgsql
        url: '%env(resolve:DATABASE_URL)%'
        # Configuración adicional para PostgreSQL
        options:
            # Codificación UTF-8 para caracteres en español
            1002: "SET NAMES 'UTF8'"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # SQLite para pruebas (más rápido)
            driver: pdo_sqlite
            url: '%env(resolve:DATABASE_URL)%'
