framework:
    default_locale: es_419
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - es
            - en
        paths:
            - '%kernel.project_dir%/translations'
